name: webstorages3 # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '2.10' # just for humans, typically '1.2+git' or '1.3.2'
summary: Backup Data on S3 in a special way # 79 char long summary
description: |
  backup data while splitting them into chunks (max 1MB) and putting them in one bucket
  saving all chunks of a file named by checksum in another bucket
  putting all files and metadata in the last bucket - thats the backupset

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  wstar:
    command: bin/wstar.py
    plugs:
      - network
      - system-backup
      - home
  fget:
    command: bin/fget.py
    plugs:
      - network
      - system-backup
      - home
  fput:
    command: bin/fput.py
    plugs:
      - network
      - system-backup
      - home
  bstool:
    command: bin/bstool.py
    plugs:
      - network
      - system-backup
      - home
  fstool:
    command: bin/fstool.py
    plugs:
      - network
      - system-backup
      - home

parts:
  webstorages3:
    # source: https://github.com/gunny26/webstorageS3.git
    source: ./
    plugin: python
#    python-version: python3
#    build-packages:
#      - python3-gpgme
#      - python3-numpy
#      - python3-pyperclip
